version: "3"
services:
  pafl:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: pafl
    volumes:
      - .:/src
    container_name: pafl_server
  prism:
    tty: true
    build:
      context: ./prism_api
      dockerfile: Dockerfile
    image: prism
    volumes:
      - ./data:/data
      - ./prism_api:/prism_api
      - ./PAFL/get_pfa_spectrum/tmp:/prism_api/tmp
    ports: 
      - 8000:8000
    container_name: prism_server